version: 2
jobs:
  build:
    parallelism: 1

    docker:
    - image: library/node:8.2.1

    branches:
      ignore:
        - /^v[0-9]/

    steps:
    - checkout
    - restore_cache:
        key: npm-cache-{{ checksum "package.json" }}
    - run: docker/scripts/retry_and_backoff.sh npm install
    - save_cache:
        key: npm-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: Update PATH and Define Environment Variable at Runtime
        command: |
          echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
          source $BASH_ENV
    - run: npm test

experimental:
  notify:
    branches:
      only:
        - master
        - release
